### ISSUE TITLE
看完了你的博客，说7件事。

### ISSUE THREAD

**Issue by jxtxzzw** [luxuantao/luxuantao.github.io#1]
看完了你的博客，说7件事。
1、不能评论啊，我还想留言额，只能在这里贴issue了。
2、seamCarving那篇文章，取颜色，其实可以用color.getRed()、color.getBlue()，当然他内部其实是(getRGB() >> 0)&0xFF。
3、文章打开的淡入淡出效果很赞。
4、网站访问速度比以前快很多了，我最近网站越来越慢了，寒假要重做我的网站了。
5、代码配色很好看，清新淡雅。
6、新手法则言之有理，也细思恐极。
7、分类如果有重的，比如这篇文章同时属于两个类，你是怎么处理的，我的分类已经一片混乱了。

**Comment by jxtxzzw** [comment]
帮你搜了一下，GitHub接入评论可以用第三方插件。参考：https://www.jianshu.com/p/b2abb157f1fa。

**Comment by luxuantao** [comment]
每次写文章要分类的时候其实我也很纠结，一般就取和它相关度最高的那个，小而精准，不用太宽泛的词，其它相关联的就写在标签里。

**Comment by luxuantao** [comment]
每次写文章要分类的时候其实我也很纠结，一般就取和它相关度最高的那个，小而精准，不用太宽泛的词，其它相关联的就写在标签里。

**Comment by luxuantao** [comment]
评论的事我也看过，好像要有自己的域名才行，等寒假里有空再研究。

**Comment by jxtxzzw** [comment]
Commit 09cf9ea，Site updated: 2018-01-18 15:27:36，里面的owner字段是不是设置有误？我看网上其他的教程，好像和你的不太一样。
